{"author":{"id":"d726bf0970d98530f2d8e7cd2738aa6327b6c5d35bb908aefb37cb65176f354e"},"ops":[{"type":1,"author":{"id":"d726bf0970d98530f2d8e7cd2738aa6327b6c5d35bb908aefb37cb65176f354e"},"timestamp":1625382532,"metadata":{"github-id":"MDU6SXNzdWU5MzYzOTQwMjM=","github-url":"https://github.com/vmiklos/osm-gimmisn/issues/1463","origin":"github"},"nonce":"C1RMKh2BMf3tnthACv9rxcCQMB0=","title":"stat: ha nincs előző időszak a havi statisztikához, akkor elszáll a frissítés","message":"Előbb kéne ellenőrizni, aztán futtatni, vagy vegye az utolsó létezőt\n\n```\n ./cron.py --mode stats --no-overpass\n2021-07-04 08:55:19 INFO update_stats: start, updating whole-country csv\n2021-07-04 08:55:22 INFO update_stats: generating json\n2021-07-04 08:55:22 ERRORmain: unhandled exception: Traceback (most recent call last):\n  File \"./cron.py\", line 385, in main\n    our_main(conf, relations, args.mode, args.update, args.overpass)\n  File \"./cron.py\", line 330, in our_main\n    update_stats(conf, overpass)\n  File \"./cron.py\", line 322, in update_stats\n    stats.generate_json(conf, statedir, stream)\n  File \"/var/lib/www/osm.vasony.hu/osm-gimmisn/stats.py\", line 217, in generate_json\n    handle_topcities(conf, state_dir, j)\n  File \"/var/lib/www/osm.vasony.hu/osm-gimmisn/stats.py\", line 91, in handle_topcities\n    ret = get_topcities(conf, src_root)\n  File \"/var/lib/www/osm.vasony.hu/osm-gimmisn/stats.py\", line 68, in get_topcities\n    with open(old_count_path, \"r\") as stream:\nFileNotFoundError: [Errno 2] No such file or directory: '/var/lib/www/osm.vasony.hu/osm-gimmisn/workdir/stats/2021-06-04.citycount'\n```","files":null}]}