{"version":2,"ops":[{"type":1,"author":{"id":"653ad5a5221de41f1bb6e2b766642806e048c3d8"},"timestamp":1617914509,"metadata":{"github-id":"MDU6SXNzdWU4NTM4Nzk0NDU=","github-url":"https://github.com/vmiklos/osm-gimmisn/issues/1225","origin":"github"},"title":"ha még nincs yaml adott területhez, a cache exception-t dob","message":"Belső hiba a /osm/missing-housenumbers/martonvasar/view-result kiszolgálása során\nTraceback (most recent call last):\n  File \"/home/osm-gimmisn/git/osm-gimmisn/wsgi.py\", line 946, in application\n    return our_application(environ, start_response)\n  File \"/home/osm-gimmisn/git/osm-gimmisn/wsgi.py\", line 929, in our_application\n    doc.asis(handler(relations, request_uri).getvalue())\n  File \"/home/osm-gimmisn/git/osm-gimmisn/wsgi.py\", line 353, in handle_missing_housenumbers\n    doc.asis(missing_housenumbers_view_res(relations, request_uri).getvalue())\n  File \"/home/osm-gimmisn/git/osm-gimmisn/wsgi.py\", line 159, in missing_housenumbers_view_res\n    doc = cache.get_missing_housenumbers_html(relation)\n  File \"/home/osm-gimmisn/git/osm-gimmisn/cache.py\", line 54, in get_missing_housenumbers_html\n    if is_missing_housenumbers_html_cached(relation):\n  File \"/home/osm-gimmisn/git/osm-gimmisn/cache.py\", line 44, in is_missing_housenumbers_html_cached\n    relation_mtime = os.path.getmtime(relation_path)\n  File \"/usr/lib64/python3.9/genericpath.py\", line 55, in getmtime\n    return os.stat(filename).st_mtime\nFileNotFoundError: [Errno 2] No such file or directory: '/home/osm-gimmisn/git/osm-gimmisn/data/relation-martonvasar.yaml'","files":null}]}